version: '3.5'

services:
  database:
    container_name: postgres_container
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: office-sync-db
      POSTGRES_HOST: localhost:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "5058:80"
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=developer@officesync.com
      - PGADMIN_DEFAULT_PASSWORD=changethis
    networks:
      - postgres
    restart: unless-stopped
  office-api:
    image: node:10.15.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - postgres
    working_dir: /app  
    command: npm run dev

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge
